version: '3.8'

services:
  # Frontend (Nginx serving static files) - Renamed to eds-frontend as per user context
  eds-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mr-dj-eds-frontend
    restart: unless-stopped
    depends_on:
      - mr-dj-backend
    networks:
      - sevensa-edge # Use the sevensa-edge network for Traefik routing
    labels:
      - "traefik.enable=true"
      # Host rule for mr-dj.sevensa.nl
      - "traefik.http.routers.mrdj-eds-frontend.rule=Host(`mr-dj.sevensa.nl`)"
      - "traefik.http.routers.mrdj-eds-frontend.entrypoints=websecure"
      - "traefik.http.routers.mrdj-eds-frontend.tls=true"
      - "traefik.http.routers.mrdj-eds-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mrdj-eds-frontend.service=mrdj-eds-frontend"
      - "traefik.http.services.mrdj-eds-frontend.loadbalancer.server.port=80"
      # Add a path prefix for the /eds route as per user requirement (Verify deployment at mr-dj.sevensa.nl/eds)
      - "traefik.http.routers.mrdj-eds-frontend-eds.rule=Host(`mr-dj.sevensa.nl`) && PathPrefix(`/eds`)"
      - "traefik.http.routers.mrdj-eds-frontend-eds.entrypoints=websecure"
      - "traefik.http.routers.mrdj-eds-frontend-eds.tls=true"
      - "traefik.http.routers.mrdj-eds-frontend-eds.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mrdj-eds-frontend-eds.service=mrdj-eds-frontend-eds"
      - "traefik.http.services.mrdj-eds-frontend-eds.loadbalancer.server.port=80"
      - "traefik.http.routers.mrdj-eds-frontend-eds.middlewares=mrdj-eds-stripprefix"
      - "traefik.http.middlewares.mrdj-eds-stripprefix.stripprefix.prefixes=/eds"

  # Backend API (Node.js/Express) - Renamed to mr-dj-backend
  mr-dj-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mr-dj-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://mrdj_user:mrdj_secure_password_2025@mr-dj-postgres:5432/mrdj_db
      JWT_SECRET: mrdj_jwt_secret_key_2025_very_secure
      CORS_ORIGIN: https://mr-dj.sevensa.nl
      REDIS_URL: redis://:mrdj_redis_password_2025@mr-dj-redis:6379/0
      REDIS_NAMESPACE: mr-dj
    depends_on:
      mr-dj-postgres:
        condition: service_healthy
      mr-dj-redis:
        condition: service_healthy
    networks:
      - sevensa-edge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mrdj-backend.rule=Host(`mr-dj.sevensa.nl`) && PathPrefix(`/api`)"
      - "traefik.http.routers.mrdj-backend.entrypoints=websecure"
      - "traefik.http.routers.mrdj-backend.tls=true"
      - "traefik.http.routers.mrdj-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.mrdj-backend.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.mrdj-backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.mrdj-backend.middlewares=mrdj-backend-stripprefix"

  # PostgreSQL Database - Renamed to mr-dj-postgres
  mr-dj-postgres:
    image: postgres:15-alpine
    container_name: mr-dj-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mrdj_db
      POSTGRES_USER: mrdj_user
      POSTGRES_PASSWORD: mrdj_secure_password_2025
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sevensa-edge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mrdj_user -d mrdj_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache (optional, voor sessions/caching) - Renamed to mr-dj-redis
  mr-dj-redis:
    image: redis:7-alpine
    container_name: mr-dj-redis
    restart: unless-stopped
    command: redis-server --requirepass mrdj_redis_password_2025
    networks:
      - sevensa-edge
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  sevensa-edge: # External network for Traefik integration
    external: true

volumes:
  postgres_data:
    driver: local

