[build]
  # Build command - install frontend deps and run the Vite production build
  command = "npm ci --prefix frontend && npm run build --prefix frontend"

  # Publish directory - where the Vite build outputs production assets
  publish = "frontend/dist"

  # Functions directory (for serverless functions if needed later)
  functions = "backend/functions"

[[build.cache]]
  # Cache the npm download directory so subsequent installs reuse tarballs
  path = "frontend/.npm"

[[build.cache]]
  # Cache the built node_modules directory for quicker local Netlify CLI runs
  path = "frontend/node_modules"

[build.environment]
  # Node version
  NODE_VERSION = "18"
  # Store the npm cache inside the frontend workspace so Netlify can persist it
  NPM_CONFIG_CACHE = "frontend/.npm"

# Redirect rules
[[redirects]]
  # Redirect /api/* to backend (if we deploy backend separately)
  from = "/api/*"
  to = "https://staging.sevensa.nl/api/:splat"
  status = 200
  force = false

[[redirects]]
  # SPA fallback - redirect all routes to index.html
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=60, stale-while-revalidate=300"

[[headers]]
  for = "/404.html"
  [headers.values]
    Cache-Control = "public, max-age=60, stale-while-revalidate=300"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Netlify Identity settings
[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "staging" }

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    output_path = "reports/lighthouse.html"

  [[plugins.inputs.budgets]]
    path = "lighthouse-budgets.json"

# Enable Netlify Forms
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
