/**
 * Structured Data (JSON-LD) Schemas for SEO
 * Generated by SEO Agent Army - Structured Data Architect
 */

export function LocalBusinessSchema() {
  const schema = {
    "@context": "https://schema.org",
    "@type": "LocalBusiness",
    "@id": "https://mr-dj.sevensa.nl/#organization",
    "name": "Mister DJ",
    "alternateName": "Mr. DJ",
    "url": "https://mr-dj.sevensa.nl",
    "logo": "https://mr-dj.sevensa.nl/assets/images/logo.webp",
    "image": "https://mr-dj.sevensa.nl/og-image.jpg",
    "description": "Professionele DJ-diensten met 100% dansgarantie voor bruiloften, bedrijfsfeesten en private events in Brabant en Zuid-Nederland. 15+ jaar ervaring, 2500+ events gedraaid.",
    "telephone": "+31-40-8422594",
    "email": "info@mr-dj.nl",
    "priceRange": "€€",
    "address": {
      "@type": "PostalAddress",
      "streetAddress": "Kapteijnlaan 17",
      "addressLocality": "Veldhoven",
      "postalCode": "5505 AV",
      "addressRegion": "Noord-Brabant",
      "addressCountry": "NL"
    },
    "geo": {
      "@type": "GeoCoordinates",
      "latitude": "51.4197",
      "longitude": "5.4017"
    },
    "areaServed": [
      {
        "@type": "City",
        "name": "Eindhoven"
      },
      {
        "@type": "City",
        "name": "Tilburg"
      },
      {
        "@type": "City",
        "name": "Den Bosch"
      },
      {
        "@type": "City",
        "name": "Breda"
      },
      {
        "@type": "State",
        "name": "Noord-Brabant"
      }
    ],
    "openingHoursSpecification": {
      "@type": "OpeningHoursSpecification",
      "dayOfWeek": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
      "opens": "09:00",
      "closes": "18:00"
    },
    "sameAs": [
      "https://www.facebook.com/misterdj",
      "https://www.instagram.com/misterdj",
      "https://www.linkedin.com/company/misterdj"
    ]
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

export function ServiceSchema() {
  const schema = {
    "@context": "https://schema.org",
    "@type": "Service",
    "serviceType": "DJ Service / Event Entertainment",
    "provider": {
      "@id": "https://mr-dj.sevensa.nl/#organization"
    },
    "areaServed": {
      "@type": "State",
      "name": "Noord-Brabant, Netherlands"
    },
    "hasOfferCatalog": {
      "@type": "OfferCatalog",
      "name": "DJ Services",
      "itemListElement": [
        {
          "@type": "Offer",
          "itemOffered": {
            "@type": "Service",
            "name": "Bruiloft DJ",
            "description": "Professionele DJ service voor bruiloften met premium geluid, licht en 100% dansgarantie"
          }
        },
        {
          "@type": "Offer",
          "itemOffered": {
            "@type": "Service",
            "name": "Bedrijfsfeest DJ",
            "description": "DJ diensten voor zakelijke events, personeelsfeesten en corporate events"
          }
        },
        {
          "@type": "Offer",
          "itemOffered": {
            "@type": "Service",
            "name": "Feest DJ",
            "description": "DJ services voor verjaardagen, jubilea en private events"
          }
        }
      ]
    },
    "aggregateRating": {
      "@type": "AggregateRating",
      "ratingValue": "5",
      "reviewCount": "2500",
      "bestRating": "5",
      "worstRating": "1"
    }
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

export function FAQSchema() {
  const schema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      {
        "@type": "Question",
        "name": "Hoe ver van tevoren moet ik boeken?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Voor bruiloften adviseren wij minimaal 6-9 maanden van tevoren te boeken, vooral in het hoogseizoen (mei-september). Voor andere feesten kan dit korter, afhankelijk van beschikbaarheid."
        }
      },
      {
        "@type": "Question",
        "name": "Wat is inbegrepen in een all-in pakket?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Een all-in pakket bevat: professionele DJ, compleet licht- en geluidsysteem, optionele photobooth, voor- en nabesprekingsgesprek, en onbeperkt muziek de hele avond. Transport en opbouw is inbegrepen."
        }
      },
      {
        "@type": "Question",
        "name": "Hoe werkt de 100% dansgarantie?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Met onze jarenlange ervaring lezen we het publiek perfect en spelen we altijd de juiste muziek op het juiste moment. Mocht de dansvloer toch leeg blijven, dan krijg je je geld terug - al is dit in 15 jaar nog nooit voorgekomen!"
        }
      },
      {
        "@type": "Question",
        "name": "Verzorgen jullie ook de ceremonie of receptie?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Ja! We kunnen de hele dag verzorgen, van ceremonie-muziek tot receptie en avondfeest. Dit bespreken we graag in een persoonlijk gesprek."
        }
      }
    ]
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

export function BreadcrumbSchema() {
  const schema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
      {
        "@type": "ListItem",
        "position": 1,
        "name": "Home",
        "item": "https://mr-dj.sevensa.nl"
      }
    ]
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

export function WebSiteSchema() {
  const schema = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": "https://mr-dj.sevensa.nl/#website",
    "url": "https://mr-dj.sevensa.nl",
    "name": "Mister DJ",
    "description": "Feest DJ Zuid Nederland - DJ Bruiloft Brabant - DJ Bedrijfsfeest",
    "publisher": {
      "@id": "https://mr-dj.sevensa.nl/#organization"
    },
    "potentialAction": [
      {
        "@type": "SearchAction",
        "target": {
          "@type": "EntryPoint",
          "urlTemplate": "https://mr-dj.sevensa.nl/?s={search_term_string}"
        },
        "query-input": "required name=search_term_string"
      }
    ],
    "inLanguage": "nl-NL"
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}
