backend:
  name: git-gateway
  branch: main

media_folder: "frontend/public/assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "pages"
    label: "Pagina's"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/homepage.json"
        fields:
          - {label: "Hero Titel", name: "hero_title", widget: "string"}
          - {label: "Hero Ondertitel", name: "hero_subtitle", widget: "text"}
          - {label: "Hero CTA Tekst", name: "hero_cta", widget: "string"}
          - {label: "Over Ons Titel", name: "about_title", widget: "string"}
          - {label: "Over Ons Tekst", name: "about_text", widget: "markdown"}
          - {label: "USP 1", name: "usp_1", widget: "string"}
          - {label: "USP 2", name: "usp_2", widget: "string"}
          - {label: "USP 3", name: "usp_3", widget: "string"}
          
  - name: "pakketten"
    label: "Pakketten"
    folder: "content/pakketten"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Naam", name: "title", widget: "string"}
      - {label: "Prijs", name: "price", widget: "number"}
      - {label: "Beschrijving", name: "description", widget: "text"}
      - {label: "Features", name: "features", widget: "list"}
      - {label: "Populair", name: "popular", widget: "boolean", default: false}
      - {label: "Volgorde", name: "order", widget: "number"}
      
  - name: "addons"
    label: "Add-ons"
    folder: "content/addons"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Naam", name: "title", widget: "string"}
      - {label: "Prijs", name: "price", widget: "number"}
      - {label: "Beschrijving", name: "description", widget: "text"}
      - {label: "Afbeelding", name: "image", widget: "image"}
      
  - name: "reviews"
    label: "Reviews"
    folder: "content/reviews"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Naam", name: "name", widget: "string"}
      - {label: "Event Type", name: "event_type", widget: "select", options: ["Bruiloft", "Bedrijfsfeest", "Verjaardag", "Anders"]}
      - {label: "Rating", name: "rating", widget: "number", min: 1, max: 5}
      - {label: "Review Tekst", name: "text", widget: "text"}
      - {label: "Datum", name: "date", widget: "date"}
      - {label: "Foto", name: "photo", widget: "image", required: false}
      
  - name: "settings"
    label: "Instellingen"
    files:
      - label: "Algemeen"
        name: "general"
        file: "content/settings/general.json"
        fields:
          - {label: "Bedrijfsnaam", name: "company_name", widget: "string"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Telefoon", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Adres", name: "address", widget: "text"}
          - {label: "KvK", name: "kvk", widget: "string"}
          - {label: "BTW", name: "btw", widget: "string"}
          - {label: "Facebook URL", name: "facebook", widget: "string", required: false}
          - {label: "Instagram URL", name: "instagram", widget: "string", required: false}
          - {label: "LinkedIn URL", name: "linkedin", widget: "string", required: false}
