backend:
  name: git-gateway
  branch: main
  
# Netlify Identity for authentication
# No need to configure - Netlify handles this automatically!

# Media storage
media_folder: "frontend/public/assets/images/uploads"
public_folder: "/assets/images/uploads"

# Site URL (will be updated after Netlify deployment)
site_url: https://mr-dj.netlify.app
display_url: https://mr-dj.netlify.app

# Logo
logo_url: /assets/images/mr_dj_logo.png

# Collections (content types)
collections:
  - name: "pages"
    label: "Pagina's"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/homepage.json"
        fields:
          - {label: "Hero Titel", name: "hero_title", widget: "string"}
          - {label: "Hero Ondertitel", name: "hero_subtitle", widget: "text"}
          - {label: "Hero CTA Tekst", name: "hero_cta", widget: "string"}
          - {label: "USP 1", name: "usp_1", widget: "string"}
          - {label: "USP 2", name: "usp_2", widget: "string"}
          - {label: "USP 3", name: "usp_3", widget: "string"}
          - {label: "Over Ons Titel", name: "about_title", widget: "string"}
          - {label: "Over Ons Tekst", name: "about_text", widget: "text"}

  - name: "pakketten"
    label: "Pakketten"
    folder: "content/pakketten"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Prijs (€)", name: "price", widget: "number"}
      - {label: "Beschrijving", name: "description", widget: "text"}
      - {label: "Volgorde", name: "order", widget: "number", default: 1}
      - {label: "Populair?", name: "popular", widget: "boolean", default: false}
      - label: "Features"
        name: "features"
        widget: "list"
        field: {label: "Feature", name: "feature", widget: "string"}

  - name: "addons"
    label: "Add-ons"
    folder: "content/addons"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Prijs (€)", name: "price", widget: "number"}
      - {label: "Beschrijving", name: "description", widget: "text"}
      - {label: "Afbeelding", name: "image", widget: "image", required: false}

  - name: "reviews"
    label: "Reviews"
    folder: "content/reviews"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Naam", name: "name", widget: "string"}
      - {label: "Event Type", name: "event_type", widget: "select", options: ["Bruiloft", "Bedrijfsfeest", "Verjaardag", "Jubileum", "Overig"]}
      - {label: "Rating (1-5)", name: "rating", widget: "number", min: 1, max: 5, value_type: "int"}
      - {label: "Review Tekst", name: "text", widget: "text"}
      - {label: "Datum", name: "date", widget: "date"}
      - {label: "Foto", name: "photo", widget: "image", required: false}

  - name: "settings"
    label: "Instellingen"
    files:
      - label: "Algemeen"
        name: "general"
        file: "content/settings/general.json"
        fields:
          - {label: "Bedrijfsnaam", name: "company_name", widget: "string"}
          - {label: "Telefoon", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Adres", name: "address", widget: "text"}
          - {label: "KvK Nummer", name: "kvk", widget: "string"}
          - {label: "Facebook URL", name: "facebook", widget: "string", required: false}
          - {label: "Instagram URL", name: "instagram", widget: "string", required: false}
          - {label: "LinkedIn URL", name: "linkedin", widget: "string", required: false}
