name: uptime-check
on:
  pull_request:
    branches: [ main ]
jobs:
  up:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
      - run: npm run start & sleep 5
      - run: curl -sf http://localhost:3000/api/health | jq .
